import os, re, json
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AGENTS = os.path.join(ROOT, "AGENTS.md")

CATS = [
    ("guards", "Guards", "Quality Gates & Validation"),
    ("tools", "Tools", "Infrastructure & Utilities"),
    ("workflow", "Workflow", "Process & Methodology"),
]

SPECIAL_SKILLS = ["desktop-control-mcp", "force-delete", "self-learning"]


def parse_skill(skill_md):
    t = open(skill_md, encoding="utf-8", errors="replace").read()
    m = re.match(r"^---\s*\n(.*?)\n---", t, re.S)
    if not m:
        return None, None
    fm = m.group(1)
    name = re.search(r"^name:\s*(.+)", fm, re.M)
    desc = re.search(r"description:\s*(\|.*)?(.+)", fm, re.S)
    n = name.group(1).strip() if name else None
    d = ""
    if desc:
        raw = desc.group(2) or ""
        d = " ".join(raw.split())
    return n, d[:80]


def scan():
    out = {}
    for key, label, purpose in CATS:
        rows = []
        base = os.path.join(ROOT, "skills", key)
        for d in sorted(os.listdir(base)):
            sm = os.path.join(base, d, "SKILL.md")
            if not os.path.isdir(os.path.join(base, d)) or not os.path.isfile(sm):
                continue
            n, desc = parse_skill(sm)
            if not n:
                n, desc = d, "(no frontmatter)"
            rows.append((n, desc))
        out[key] = rows
    special = []
    for name in SPECIAL_SKILLS:
        sm = os.path.join(ROOT, "skills", name, "SKILL.md")
        if os.path.isfile(sm):
            n, desc = parse_skill(sm)
            special.append((n or name, desc or "(no frontmatter)"))
    out["special"] = special
    return out


def render(idx):
    lines = []
    total = sum(len(v) for v in idx.values())
    lines.append(
        f"## 4. Skill Index ({total} Skills - Auto-generated {datetime.now(timezone.utc).strftime('%Y-%m-%d')})"
    )
    lines.append("")
    lines.append("> AUTO-GENERATED by tools/build_index.py - do not hand-edit. Run: python tools/build_index.py")
    lines.append("")
    for key, label, purpose in CATS:
        rows = idx[key]
        lines.append(f"### {label} ({len(rows)}) - {purpose}")
        lines.append("| Skill | Purpose |")
        lines.append("|-------|---------|")
        for n, d in rows:
            lines.append(f"| {n} | {d} |")
        lines.append("")
    if idx.get("special"):
        lines.append(f"### Special ({len(idx['special'])}) - Top-level cross-cutting skills")
        lines.append("| Skill | Purpose |")
        lines.append("|-------|---------|")
        for n, d in idx["special"]:
            lines.append(f"| {n} | {d} |")
        lines.append("")
    return "\n".join(lines), total


def main():
    idx = scan()
    block, total = render(idx)

    t = open(AGENTS, encoding="utf-8").read()
    start = t.find("## 4. Skill Index")
    if start == -1:
        print("ERROR: Skill Index section not found")
        return
    nxt = re.search(r"\n## 5\b|\n---\n\n## ", t[start:])
    end = start + (nxt.start() if nxt else len(t) - start)
    new_t = t[:start] + block + "\n\n" + t[end:].lstrip("\n")
    # normalize spacing before next section
    open(AGENTS, "w", encoding="utf-8", newline="\r\n").write(new_t)

    counts = {k: len(v) for k, v in idx.items()}
    print(json.dumps({"total": total, **counts}))
    # also dump machine-readable index
    jp = os.path.join(ROOT, "skills_index.json")
    json.dump(
        {
            "generated": datetime.now(timezone.utc).isoformat(),
            "counts": counts,
            "index": {k: [{"name": n, "desc": d} for n, d in v] for k, v in idx.items()},
        },
        open(jp, "w", encoding="utf-8"),
        indent=1,
    )


if __name__ == "__main__":
    main()
